[package]
name = "trayapp"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.7"
tray-item = "0.8.0"

[target.'cfg(unix)'.dependencies]
tray-item = { version = "0.8.0", features = ["ksni"] }

[target.'cfg(windows)'.build-dependencies]
windres = "*"